# Private DNS: the server's name resolves to its private IP, only inside the VNet.
resource "azurerm_private_dns_zone" "postgres" {
  name                = "${var.project}.private.postgres.database.azure.com"
  resource_group_name = azurerm_resource_group.main.name
  tags                = local.tags
}

resource "azurerm_private_dns_zone_virtual_network_link" "postgres" {
  name                  = "link-${var.project}-vnet"
  resource_group_name   = azurerm_resource_group.main.name
  private_dns_zone_name = azurerm_private_dns_zone.postgres.name
  virtual_network_id    = azurerm_virtual_network.main.id
  registration_enabled  = false
  tags                  = local.tags
}

# Strong admin password, generated by Terraform and stored only in Key Vault (never typed or committed).
resource "random_password" "db_admin" {
  length           = 32
  special          = true
  override_special = "!#%*-_=+"
  min_lower        = 2
  min_upper        = 2
  min_numeric      = 2
  min_special      = 2
}

resource "azurerm_key_vault_secret" "db_admin_password" {
  name = "db-admin-password"

  value        = random_password.db_admin.result
  key_vault_id = azurerm_key_vault.main.id
  content_type = "PostgreSQL admin password for pgadmin"

  depends_on = [azurerm_role_assignment.kv_admin]
}

# Private-only PostgreSQL: lives inside snet-db, no public endpoint.
resource "azurerm_postgresql_flexible_server" "main" {
  name                          = "psql-${var.project}-${random_string.kv_suffix.result}"
  resource_group_name           = azurerm_resource_group.main.name
  location                      = var.workload_location
  version                       = "16"
  delegated_subnet_id           = azurerm_subnet.db.id
  private_dns_zone_id           = azurerm_private_dns_zone.postgres.id
  public_network_access_enabled = false
  administrator_login           = "pgadmin"
  administrator_password        = random_password.db_admin.result
  sku_name                      = "B_Standard_B1ms"
  storage_mb                    = 32768
  backup_retention_days         = 7
  geo_redundant_backup_enabled  = false
  auto_grow_enabled             = false
  tags                          = local.tags

  depends_on = [
    azurerm_private_dns_zone_virtual_network_link.postgres,
    azurerm_subnet_network_security_group_association.db,
  ]

  lifecycle {
    ignore_changes = [zone]

  }
}

resource "azurerm_postgresql_flexible_server_database" "tripdb" {
  name      = "tripdb"
  server_id = azurerm_postgresql_flexible_server.main.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}
