apiVersion: v1
kind: Service
metadata:
  name: trip-tracker
  namespace: trip-tracker
  annotations:
    service.beta.kubernetes.io/azure-pip-name: pip-trip-tracker-app           # our Terraform IP
    service.beta.kubernetes.io/azure-load-balancer-resource-group: rg-trip-tracker
spec:
  type: LoadBalancer
  selector:
    app: trip-tracker
  ports:
    - name: http
      port: 80            # what the browser hits
      targetPort: http    # container port 8000
